version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"   # Edge Agent
      - "9000:9000"   # HTTP
      - "9443:9443"   # HTTPS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      # Опциональные переменные окружения
      - PORTAINER_LOG_LEVEL=INFO
    labels:
      - "com.example.description=Portainer Container Management"
      - "com.example.version=latest"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  portainer_data:
    driver: local
    labels:
      - "com.example.description=Portainer data volume"

# Дополнительная конфигурация для production
# networks:
#   portainer_network:
#     driver: bridge
#     labels:
#       - "com.example.description=Portainer network"
